### ISSUE TITLE
Add authentication

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/dalgo-admin#2]
## Description
Add Google authentication for login

## Goals
- [x] Login with Google account

## Expected Outcome
Users with an @projecttech4dev.org email address should be able to log into the application

## Acceptance Criteria
- [x] A login screen
- [x] User accounts in the database
- [x] Look up User via Google auth token
- [x] View showing the User object's fields after successful login

## Implementation Details
Use the `django-allauth` library. The steps listed [here](https://pylessons.com/django-google-oauth) should help

## Mockups / Wireframes
None

### Product Name
Dalgo

### Project Name
Dalgo Admin Console

### Organization Name:
Project Tech4Dev

### Domain
Others

### Tech Skills Needed:
Python

### Mentor(s)
@fatchat 

### Complexity
Medium

### Category
Feature

### Sub Category
Frontend, Backend, Beginner friendly

**Comment by priyakumari02** [comment]
@fatchat   , Can I work on this issue , I believe the skills of this project align to my skills. I would like to work on this issue.

**Comment by anivenk25** [comment]
Hi @fatchat , I'm eager to take on the challenge of working on this issue, as I believe my skills align perfectly with the requirements. Having successfully designed similar pages for my projects, I'm confident in my ability to contribute effectively.

**Comment by fatchat** [comment]
hello @priyakumari02 and @anivenk25 

you are both welcome to work on this, but you will notice that @jayesh9747 already assigned it to himself. please discuss here amongst yourselves and figure out who will do it

thanks everyone

**Comment by priyakumari02** [comment]
Sure @jaiakash

**Comment by kumar20vinay** [comment]
hi @ravi-prakash-v ,
I am good with the backend and have already worked on a couple of projects.
Can you please assign it to me?

**Comment by fatchat** [comment]
good morning @kumar20vinay 
i think you meant to comment on the beckn project?
