### ISSUE TITLE
Parse monitoring data for the infrastructure page

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/dalgo-admin#21]
## Description
The infrastructure page currently displays hardcoded values for CPU, RAM and available disk space. The goal of this PR is to fetch live values from the existing monitoring system.

The monitoring system exposes an endpoint which the `dalgo-admin` server can fetch from. For this PR you must make this endpoint configurable via `.env`

## Goals
- [ ] Inspect the `assets/promtail_output.txt` file and figure out how to find the relevant information
- [ ] Write a function to fetch this data from the monitoring service
- [ ] Parse the data to extract the relevant fields
- [ ] Populate the existing infrastructure template with these live values

## Expected Outcome
With the correct `.env` settings I should be able to see live monitoring data on the infrastructure page

## Acceptance Criteria
- [ ] In development you should see metrics from `assets/promtail_output.txt` on the infrastructure page. Once I deploy in production I will see live metrics.

## Implementation Details
In development you will not be able to fetch live data due to firewall restrictions. In order to test your PR, please mock the response by returning the contents of `assets/promtail_output.txt`. This should be controlled via another `.env` variable

## Mockups / Wireframes
None

### Product Name
Dalgo

### Project Name
Dalgo Admin Console

### Organization Name:
Project Tech4Dev

### Domain
Others

### Tech Skills Needed:
Python, requests

### Mentor(s)
@fatchat 

### Complexity
Medium

### Category
Feature

### Sub Category
API, Backend

**Comment by yaswanthsaivendra** [comment]
Hey @fatchat 
I got this. Can I work on this issue?

**Comment by fatchat** [comment]
@yaswanthsaivendra sure go for it

**Comment by jayesh9747** [comment]
@fatchat  I want to work on this issue , can you assign me ?

**Comment by Sandeep0306** [comment]
Hi, @fatchat I would like to work on this issue. Can you assign it to me?

**Comment by fatchat** [comment]
@Sandeep0306 @senku-177 you are free to submit a PR, @jayesh9747 is also working on it but the first successful PR will be merged

**Comment by jayesh9747** [comment]
@senku-177 @Sandeep0306  i almost complete task of pr and you help me out to review my pr ?

**Comment by AnuRage-git** [comment]
@fatchat Can I get the status of this issue? If it hasn't been done yet, I'd like to work on it

**Comment by fatchat** [comment]
@AnuRage-git there is an open PR which may close it, which I haven't gotten around to reviewing yet

**Comment by AnuRage-git** [comment]
I can test it on diff environments and confirm the changes made if required

**Comment by AnuRage-git** [comment]
I can test it on diff environments and confirm the changes made if required
