### ISSUE TITLE
Create a Client Overview page

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/dalgo-admin#4]
## Description
A page in the application which provides an overview of Dalgo clients

## Goals
- [x] Table of clients
- [x] Select to show a detailed view in a separate panel

## Expected Outcome
The page will fetch the required data from the backend and render it in a table. The rows should be sorted by the "Name" column

## Acceptance Criteria
- [x] Name column
- [x] Warehouse type column
- [x] Number of data sources column
- [x] Number of pipelines column
- [x] Column indicating whether or not GitHub has been connected
- [x] Details panel showing the above details + last sync date for each connection + GitHub repo url

## Implementation Details
Bootstrap 5

## Mockups / Wireframes
None

### Product Name
Dalgo

### Project Name
Dalgo Admin Console

### Organization Name:
Project Tech4Dev

### Domain
Others

### Tech Skills Needed:
Python
HTML
Bootstrap
SQL

### Mentor(s)
@fatchat 

### Complexity
Medium

### Category
UI/UX/Design, Feature

### Sub Category
API, Database, Frontend, Backend, Mobile

**Comment by jayesh9747** [comment]
hello   @fatchat  i want to work on this API -frontend issue , can I going to start work on this issue ?

**Comment by fatchat** [comment]
hi @jayesh9747 are you not working on authentication then

**Comment by fatchat** [comment]
for this issue we will need to get data via an api, and for that we need authentication to be done

**Comment by jayesh9747** [comment]
hello @fatchat  , I want to contribute in the authentication  but I need some time to learn django framework cause I make auth with passport.js in nodejs but I am sure to be well in django also then I continue this issue#4

**Comment by jayesh9747** [comment]
so firstly i collab in auth also for grabbing more knowledge in django

**Comment by fatchat** [comment]
ok fair enough... then for now you can build the UI using dummy data. later we will replace that with an API call

**Comment by jayesh9747** [comment]
Hello, @fatchat! In this issue, when clicking on a row, the details should be displayed in a separate panel, indicating the use of a modal to present specific client information.

**Comment by fatchat** [comment]
@jayesh9747 that sounds good, maybe a sidebar which opens from the right hand side

**Comment by jayesh9747** [comment]
@fatchat i think that on the table each row view button and model is open for detail information of client it is more preferable or not ?  
![image](https://github.com/DalgoT4D/dalgo-admin/assets/123955234/0da58d4d-2d4c-4b42-8487-a29d9bcd369d)
![image](https://github.com/DalgoT4D/dalgo-admin/assets/123955234/5f5bd7df-ab3f-4d6e-8f81-c642c4f48fa6)

**Comment by jayesh9747** [comment]
@fatchat  can you give an idea about in detail , what the dalgo-admin project does? is there any documentation about this project?

**Comment by fatchat** [comment]
@jayesh9747 does this help? https://github.com/DalgoT4D/dalgo-admin/wiki/Client-view

**Comment by amansgith** [comment]
Hi @jayesh9747 let's divide the work into two parts
1. Making table and fetching data
2. Making the side pane for more details 
After it's done you may make the final pr..
Alright?

Hi Sir @fatchat can you tell me that is the data being fetched from postgres or any other platform for the table?

**Comment by fatchat** [comment]
@amansgith the data will come from an API call. I still have to build this API, for now you can fake it i.e. in your controller you will have functions like `get_clients` and `get_client`. these will call my API in future, for now they can return some fake data

**Comment by fatchat** [comment]
since you don't know how big some of these string responses will be, make sure to truncate them to a sensible length before rendering

**Comment by jayesh9747** [comment]
Now, let's simulate the backend by sending some mock data, and upon completion, display the details in the side panel when a row is clicked.

**Comment by amansgith** [comment]
@fatchat sure sir!

Yeah @jayesh9747 take up any one part you want to do.. and I will do the other one

**Comment by amansgith** [comment]
@jayesh9747 It's totally up to you brother!!
You asked for this issue first 
If you want to handle both.. it's ok 
otherwise it will be easier to work by splitting up work and push on the same branch

**Comment by jayesh9747** [comment]
@amansgith, let's do it together, most preferably I want to work on the first part which is building a model and fetching data.

**Comment by amansgith** [comment]
Ok @jayesh9747  Go ahead, complete the first part and after your are done with it.. I will add the side pane for the data table

**Comment by jayesh9747** [comment]
@amansgith, I apologize, but I managed to resolve the entire issue on my own. Could you please focus your efforts on issue #7?

**Comment by amansgith** [comment]
No worries!!
I'm glad you were able to do it... ofc its not a very complex issue
go ahead!! 👍

**Comment by jayesh9747** [comment]
@fatchat  please close this issue and any new issue available for contribute?

**Comment by Viswaraje** [comment]
@fatchat I am interested to contribute to the issues in the repository.Could you please assign issues to solve ?Thanks.I am a full stack enthusiast and would love to work on the issues in the repository.Please assign me the issues.

**Comment by amansgith** [comment]
> @fatchat I am interested to contribute to the issues in the repository.Could you please assign issues to solve ?Thanks.I am a full stack enthusiast and would love to work on the issues in the repository.Please assign me the issues.
> 
> 

@Viswaraje this issue is already closed.. please look for other issues
