### ISSUE TITLE
Frontend Toolbar

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/dalgo-admin#7]
## Description
Add a toolbar to the frontend. This should appear at the top of every page.

## Goals
- [ ] Add a toolbar
- [ ] Works on mobile

## Expected Outcome
Every page added to the frontend should contain the toolbar. The toolbar will have a logo at the left end which routes the user to the home page. At the right we will have a drop-down menu. For this first version the drop-down will have only one item - "Logout". In the center we will have the text "Dalgo Admin Console"

## Acceptance Criteria
- [ ] Works on desktop
- [ ] Works on mobile
- [ ] Easy for other developers to add menu items

## Implementation Details
Use Bootstrap 5

## Mockups / Wireframes
None

### Product Name
Dalgo

### Project Name
Dalgo Admin Console

### Organization Name:
Project Tech4Dev

### Domain
Others

### Tech Skills Needed:
Python
HTML
CSS

### Mentor(s)
@fatchat 

### Complexity
Low

### Category
UI/UX/Design, Feature

### Sub Category
Frontend, Mobile, Beginner friendly

**Comment by KDwevedi** [comment]
comment

**Comment by amansgith** [comment]
Hello Sir @fatchat  i would like to work on this issue under your guidance.. 
i have some questions regarding this issue:
1. Is the toolbar actually a navigation bar to be placed on the top of the website?
2. Also which repository i have to clone to work on this issue?

**Comment by fatchat** [comment]
Hello @amansgith the project has not started yet but I can let you know when it does. Thanks for your interest

**Comment by srishtiagarwall** [comment]
Greetings, Sir @fatchat I would like to collaborate with you on this issue.

**Comment by srishtiagarwall** [comment]
Hello @fatchat,

Thank you for the update. I'm ready to get started on the project. I'll head over to issue #12 to collaborate on this. I look forward to contributing!

**Comment by fatchat** [comment]
sure @Shubh-Goyal-07 , head over to the discussion linked above

**Comment by Shubh-Goyal-07** [comment]
Sure sir @fatchat 
Heading over to #12 
Thank You.

**Comment by Shubh-Goyal-07** [comment]
Sir @fatchat I would like to work on this issue. Requesting you to assign the issue.

**Comment by priyakumari02** [comment]
@fatchat   , Can I work on this issue , I believe the skills of this project align to my skills. I would like to work on this issue.

**Comment by fatchat** [comment]
happy to have you @priyakumari02 , go over to the discussion linked above to catch up

**Comment by Shubh-Goyal-07** [comment]
Sir @fatchat, wanted to confirm if bootstrap should be used or raw CSS is preferred?

**Comment by fatchat** [comment]
@Shubh-Goyal-07 definitely not raw CSS. I think Bootstrap is a good choice since it is widely known and supported, i.e. there are many developers who will be able to contribute to this project if we use BS

**Comment by Prathamesh12111** [comment]
@fatchat I would like to work on this issue. Requesting you to assign the issue.

**Comment by Prayant-M** [comment]
Hello, I would like to collaborate on this issue

**Comment by fatchat** [comment]
@Shubh-Goyal-07 are you working on this? if you're busy i'd like to give someone else a chance

**Comment by jayesh9747** [comment]
@fatchat  can I start work on this?

**Comment by Shubh-Goyal-07** [comment]
Sir @fatchat, this is the first design I made for the toolbar. Can you please verify it?

![Screenshot from 2024-02-02 13-35-38](https://github.com/DalgoT4D/dalgo-admin/assets/92088100/ec2e9243-20d0-4ed7-8f1c-f54346de0107)

**Comment by Shubh-Goyal-07** [comment]
@fatchat would like to confirm if the fonts used and the color theme must align with the Dalgo page?

**Comment by fatchat** [comment]
Not necessarily

**Comment by amansgith** [comment]
Hii @Shubh-Goyal-07 make sure that you add the toolbar to every page of the Dalgo Admin Website.. I also suggest that you can try to include it in a base.html and then let other files inherit that base.html.. or as a component which will be inherited by diffferent html pages

**Comment by fatchat** [comment]
In base.html sounds good… other pages should have no knowledge of the
toolbar

Or of the side menu

**Comment by Shubh-Goyal-07** [comment]
Yeah... I have made an admin.html as the base file and the toolbar is being imported into it. We will be able to use it in every page later on.

**Comment by fatchat** [comment]
@Shubh-Goyal-07 and @vilol-04 

you are both working on issues which are somewhat related
- toolbar
- sidemenu

similarities:
- both should appear when user is logged in
- other pages should not "know about" these components

difference:
- toolbar also appears when user is logged out, sidemenu does not

@vilol-04 i believe @Shubh-Goyal-07 has made progress towards this goal, you may want to see what he has done and adapt your code accordingly

thank you both

**Comment by Shubh-Goyal-07** [comment]
Sure @vilol-04, severus#2725 is my discord id.

Also sir @fatchat, if you permit may I create a PR to push the current toolbar. This will let others use the basic template for all the issues and also the sidebar will easily get integrated in it. I will later on make it completely responsive and make another PR in a couple of days.

**Comment by vilol-04** [comment]
@Shubh-Goyal-07 I can't find you. Can you dm me? @V_goyal is my id.

**Comment by Shubh-Goyal-07** [comment]
@vilol-04 can't find your name too. Can you search come online and search for someone with name enigma on C4GT server.

**Comment by fatchat** [comment]
@Shubh-Goyal-07 ok that's a good idea, will be helpful to have the framework and then iterate upon it separately

**Comment by Shubh-Goyal-07** [comment]
Sir @fatchat there is a conflict regarding the path to the admin page, currently it has been set to the base link whereas I did set it to be at /dalgo_admin/ after the base link. What should be used. Also, should the templates folder be kept in the main directory or in the dalgo_admin_app folder.

**Comment by fatchat** [comment]
@Shubh-Goyal-07 it sounds like you have two questions
1. url structure
2. project folder structure

for (1), by "admin page" do you mean home? in the `urls.py` of the main branch, home is attached the to path `''` which is fine. or let me know if i have misunderstood your question

regarding (2), it looks like the application is running fine with the templates inside `dalgo_admin_app` so let's leave it like that
