### ISSUE TITLE
Add a Side Menu

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/dalgo-admin#8]
## Description
Add a side menu to the application

## Goals
- [ ] [A hideable side menu]
- [ ] [Hidden by default on mobile view]

## Expected Outcome
A vertical menu on the left hand side of the layout. Visible by default on desktops, hidden by default on mobile. Toggle visibility by clicking a hamburger icon at the top

## Acceptance Criteria
- [ ] [Visible by default on desktop]
- [ ] [Hidden by default on mobile]
- [ ] [Toggle visibility]
- [ ] [Easy for developers to add menu items]
- [ ] [Menu items are attached to routes]
- [ ] [Possible to add separators]
- [ ] [Two sets of menu items - top set and bottom set. Bottom set can be empty]

## Implementation Details
Bootstrap 5

## Mockups / Wireframes
None

### Product Name
Dalgo

### Project Name
Dalgo Admin Console

### Organization Name:
Project Tech4Dev

### Domain
Others

### Tech Skills Needed:
HTML

### Mentor(s)
@fatchat 

### Complexity
Low

### Category
UI/UX/Design, Feature

### Sub Category
Frontend, Mobile, Beginner friendly

**Comment by Shruti3004** [comment]
update

**Comment by Shruti3004** [comment]
update

**Comment by Ankitapanda25** [comment]
hello, 
I have gone through the description of the project and I am interested to work on this. I believe I have got the required skills and just require your guidence through this..

**Comment by fatchat** [comment]
hi @Ankitapanda25 thanks for your interest. the project hasn't been set up yet, this will be done by some college students this month as part of a community program. please subscribe to updates so you can track our progress. i will be glad for your contributions

**Comment by Ankitapanda25** [comment]
@fatchat yes sure, would love to work on it once it has been set up

**Comment by srishtiagarwall** [comment]
Greetings, Sir @fatchat - As I've understood the issue, I would like to collaborate with you on this issue under your guidance.

**Comment by fatchat** [comment]
hello @Ankitapanda25 and @srishtiagarwall 

If you are ready we can get started on this project. Please head over to

https://github.com/DalgoT4D/dalgo-admin/discussions/12

**Comment by srishtiagarwall** [comment]
Hello @fatchat,

Thank you for the update. I'm ready to get started on the project. I'll head over to issue #12 to collaborate on this. I look forward to contributing!

**Comment by Ankitapanda25** [comment]
hello @fatchat yes, thanks. I am ready to get started on this project.

**Comment by AdityaGupta2804** [comment]
Hello @fatchat , having grasped the essence of the matter, I express my interest in working collaboratively on this issue, seeking your guidance throughout the process.

**Comment by yashvikram30** [comment]
Hello Sir! I have looked through the details of the project and I am interested in contributing to the same. @fatchat sir, looking forward for your mentorship and guidance in the process.

**Comment by harshit6174** [comment]
hello @fatchat sir, I have gone through the requirements of the project , And i would love to work on this project under your guidance

**Comment by vilol-04** [comment]
hi @fatchat . I am interested to work on this issue.

**Comment by Crystal11101** [comment]
Hi @fatchat I would like to work on this issue

**Comment by ishanray1234** [comment]
Hi @fatchat I would like to work on the issue.

**Comment by swadhin1237** [comment]
Hi @fatchat I would like to work on this issue

**Comment by fatchat** [comment]
so much interest! i have no basis upon which to assign the issue to any one of you, please discuss amongst yourselves and decide. remember that reviewing a PR is also a form of contribution

**Comment by abansal15** [comment]
Hello @Bhavik-ag can you please assign it to me

**Comment by fatchat** [comment]
so much interest but nobody has submitted a PR for me to review! 

when there are many people asking for assignment i'm not going to be able to choose one. you can either

1. discuss it on the C4GT discord server in the #tech4dev channel
2. just do the work and submit a PR

i'll accept the first PR which gives us a good side menu

**Comment by EeshNaugraiya** [comment]
please assign this issue to me I want to work on it I have understood it properly

**Comment by fatchat** [comment]
> please assign this issue to me I want to work on it I have understood it properly

hi @EeshNaugraiya please read my comment which is directly above your message

**Comment by SanjayRam07** [comment]
hello @fatchat  , can I work on this issue?
Could you please assign and mentor me?

**Comment by ayerhssb** [comment]
Greetings, @fatchat  - I've understood the issue and I would like to collaborate on this issue.
